Drivers: add drivers to support RoboSense LiDAR
ApolloAuto/apollo pull request #12348
Opened 2020-09-02 07:58 UTC by yfcube

2020-09-02 08:32 UTC, storypku commented on modules/drivers/robosense/BUILD
> +    linkopts = ["-shared"],
This line should be removed. See #12349 for a reference.
And, what about introducing a  `ROBOSENSE_COPTS` variable to be shared across the whole BUILD file, just like 
'HESAI_COPTS' in the forementioned PR.

2020-09-02 10:13 UTC, storypku reviewed
Thanks again for your PR.  It looks OK to me now. @Capri2014 @xiaoxq 
@jinghaomiao @ycool for final review opinion.

2020-09-18 14:26 UTC, fengqikai1414 requested changes

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/input/input.cpp
> +    std::cerr << "socket: " << std::strerror(errno) << std::endl;
请统一使用apollo日志接口 AERROR

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/driver/utility.h
> +class ThreadPool {
为什么不使用apollo提供的线程池

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/dag/rs128.dag
> +    module_library : "/apollo/bazel-bin/modules/drivers/velodyne/compensator/libvelodyne_compensator_component.so"
路径名不应该是velodyne

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/dag/rs16.dag
> +    module_library : "/apollo/bazel-bin/modules/drivers/velodyne/compensator/libvelodyne_compensator_component.so"
不应该使用velodyne

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/dag/rs32.dag
> +    module_library : "/apollo/bazel-bin/modules/drivers/velodyne/compensator/libvelodyne_compensator_component.so"
不应用使用velodyne

2020-09-18 14:26 UTC, fengqikai1414 commented on modules/drivers/robosense/dag/rsbp.dag
> +    module_library : "/apollo/bazel-bin/modules/drivers/velodyne/compensator/libvelodyne_compensator_component.so"
不应该使用velodyne

2020-09-21 03:08 UTC, CrazyTomX commented on modules/drivers/robosense/dag/rs128.dag
> +    module_library : "/apollo/bazel-bin/modules/drivers/velodyne/compensator/libvelodyne_compensator_component.so"
![image](https://user-images.githubusercontent.com/32247692/93730302-a06b3e00-fbfa-11ea-8755-e01712e3fd07.png)
 您好，我们是参考了apollo文档 how_to_add_a_new_lidar_driver中写的可以复用velodyne的运动补偿模块

2020-10-10 08:34 UTC, fengqikai1414 approved these changes

2020-10-12 02:56 UTC, merged