Change scripts which use "pgrep" to avoid PID 1.
ApolloAuto/apollo pull request #12360
Opened 2020-09-03 04:53 UTC by rongguodong

Apollo uses {{pgrep -c -f}} to determine if processes are running. Unfortunately, this finds them in the inline container startup command. 

This change uses of {{pgrep -f}} to ignore when PID 1 is output by filtering the output with {{| grep -v '^1$'}}. For the cases where {{-c}} is also supplied, using {{| wc -l}} to count the lines of the output.

2020-09-03 04:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=12360) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=12360) before we can accept your contribution.<br/><hr/>**Guodong Rong** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ApolloAuto/apollo?pullRequest=12360) it.</sub>

2020-09-03 11:37 UTC, storypku commented
> Apollo uses **pgrep -c -f** to determine if processes are running. Unfortunately, this finds them in the inline container startup command. This is a problem when we try to run Apollo in our own container on cloud where the container startup command contains some strings matching Apollo's pgrep string.
> 
> This change uses of **pgrep -f** to ignore when PID 1 is output by filtering the output with **| grep -v '^1$'**, and use **| wc -l** to count the lines of the output.

Can you further explain the situation in your case? I didn't quite get what you means by saying "this finds them in the inline container startup command". It seems that you want to exclude PID 1 ( On a normal Linux host, pid 1 is for the init process). Maybe it's related to docker ? Can you give us a minimal environment to reproduce the case?

BTW,  we can use `grep -cv '^1$' ` to count all pids that are not 1.

2020-09-03 11:38 UTC, storypku requested changes
Please provide more details and change `grep -v | wc -l` operation to `grep -cv`.

2020-09-03 21:50 UTC, rongguodong commented
We use an inline startup script when launching our Apollo containers under Kubernetes. (A container's startup script is always PID 1 under Kubernetes.) What is meant by "inline" is that script is passed as one long string to "bash -c", and therefore appears in its entirety, including any comments, in the command line that "pgrep -f" searches. While developing the script, things inexplicably stopped working. Imagine our surprise when, after a many hours of debugging, it turned out that the cause was a comment mentioning "cyber_recorder" had been added to the script and the Apollo code now considered it to be running.

Because it matches substrings anywhere in the command line, using "pgrep -f" makes it easy for there to be unexpected side-effects. For example, "pgrep -f modules/dreamview/launch/dreamview.launch" outputs the PID for "vi modules/dreamview/launch/dreamview.launch". And if the container is run with --pid=host, it would find such a vi running on the host outside of the container! It would be much safer to use "pgrep -x", but it was more expedient for us to just filter out PID 1.

2020-09-03 21:55 UTC, rongguodong commented
@storypku If you want to reproduce it locally, you may change dev_start.sh as following:
* Remove [this line](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L530); and
* Change [this line](https://github.com/ApolloAuto/apollo/blob/master/docker/scripts/dev_start.sh#L533) to the following line:
/bin/bash -c ": cyber_recorder; sleep inf"

After you do "dev_start.sh" and "dev_into.sh", "ps aux" will show something like:
[guodong@in-dev-docker:/apollo]$ ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.0  18376  3004 pts/1    Ss+  14:45   0:00 /bin/bash -c : cyber_recorder; sleep 
root         6  0.0  0.0   4532   880 pts/1    S+   14:45   0:00 sleep inf
guodong     60  1.0  0.0  19444  4448 pts/2    Ss   14:45   0:00 /bin/bash
guodong     88  0.0  0.0  34404  2856 pts/2    R+   14:45   0:00 ps aux

And if you use pgrep -f "cyber_recorder", you will get "1".

2020-09-03 22:01 UTC, rongguodong commented
> Please provide more details and change `grep -v | wc -l` operation to `grep -cv`.

Done.

2020-09-03 23:27 UTC, storypku commented
> We use an inline startup script when launching our Apollo containers under Kubernetes. (A container's startup script is always PID 1 under Kubernetes.) What is meant by "inline" is that script is passed as one long string to "bash -c", and therefore appears in its entirety, including any comments, in the command line that "pgrep -f" searches. While developing the script, things inexplicably stopped working. Imagine our surprise when, after a many hours of debugging, it turned out that the cause was a comment mentioning "cyber_recorder" had been added to the script and the Apollo code now considered it to be running.
> 
> Because it matches substrings anywhere in the command line, using "pgrep -f" makes it easy for there to be unexpected side-effects. For example, "pgrep -f modules/dreamview/launch/dreamview.launch" outputs the PID for "vi modules/dreamview/launch/dreamview.launch". And if the container is run with --pid=host, it would find such a vi running on the host outside of the container! It would be much safer to use "pgrep -x", but it was more expedient for us to just filter out PID 1.

Thanks for your details explanation. Maybe the team should modify these scripts to avoid the `vim modules/dreamview/launch/dreamview.launch` case you mentioned in next PRs.

Regards,
Jiaming Liu

2020-09-03 23:28 UTC, storypku approved these changes

2020-09-03 23:28 UTC, merged

2020-09-03 23:35 UTC, rongguodong commented
Is `--pid=host` only needed for debugging? If you remove this line, you cannot see processes running outside of the docker.
For our use case, we just need to run Apollo on the cloud and do not need any debugging. Is it safe to simply remove this line?

2020-09-03 23:44 UTC, storypku commented
> Is `--pid=host` only needed for debugging? If you remove this line, you cannot see processes running outside of the docker.
> For our use case, we just need to run Apollo on the cloud and do not need any debugging. Is it safe to simply remove this line?

I will do some investigation first. 
Would you please file an issue for the `--pid=host` thing ?
Thank you.

2020-09-08 21:18 UTC, HongyiSun commented
There is a problem cause by escape characters in pythons, where `'` in the python string was misinterpreted. I have made a PR #12443 on fixing this.