Doc: DKIT add control profiling online guide
ApolloAuto/apollo pull request #12389
Opened 2020-09-04 11:55 UTC by macDure

2020-09-04 15:44 UTC, storypku commented on docs/specs/D-kit/Waypoint_Following/Control_profiling_Online_cn.md
> +- [循迹搭建--车辆循迹演示](Start_Waypoint_Following_cn)
.md

2020-09-04 15:47 UTC, storypku requested changes

2020-09-04 15:47 UTC, storypku commented on docs/specs/D-kit/Waypoint_Following/Control_profiling_Online_cn.md
> +- 通过使用`cyber`命令来检查采集数据内是否存在上述`channel`的数据：
cyber_recorder

2020-09-04 21:13 UTC, kevin-y-wang commented
Great job! The only thing is that in the figure control_profiling_online_folder_structure.png, there is a typo in the title that "syetem"  should be "system". This is a historical typo. You may try to PS it or if easier, directly remove this title line from the figure.

2020-09-05 03:22 UTC, macDure commented on docs/specs/D-kit/Waypoint_Following/Control_profiling_Online_cn.md
> +- [循迹搭建--车辆循迹演示](Start_Waypoint_Following_cn)
thank you

2020-09-05 06:33 UTC, macDure commented on docs/specs/D-kit/Waypoint_Following/Control_profiling_Online_cn.md
> +- 通过使用`cyber`命令来检查采集数据内是否存在上述`channel`的数据：
thanks

2020-09-05 06:49 UTC, macDure commented
> Great job! The only thing is that in the figure control_profiling_online_folder_structure.png, there is a typo in the title that "syetem" should be "system". This is a historical typo. You may try to PS it or if easier, directly remove this title line from the figure.

Have fixed, thank you.

2020-09-05 22:46 UTC, kevin-y-wang approved these changes

2020-09-07 02:34 UTC, storypku approved these changes

2020-09-07 02:36 UTC, merged