Calibration:add a new vehicle configuration files
ApolloAuto/apollo pull request #12380
Opened 2020-09-04 06:58 UTC by cuishiwei

2020-09-04 06:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=12380) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=12380) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ApolloAuto/apollo?pullRequest=12380) it.</sub>

2020-09-04 07:36 UTC, macDure commented on modules/calibration/data/dev_kit_standard/vehicle_info.pb.txt
> +    vin : "ch05"
change the devkit01

2020-09-04 07:36 UTC, macDure commented on modules/calibration/data/dev_kit_standard/gnss_conf/gnss_conf.pb.txt
> +        baud_rate: 460800
change it to 115200

2020-09-04 08:33 UTC, diegohu requested changes
Add modules/calibration/data/dev_kit/cancard_params/canbus.conf and remove modules/calibration/data/dev_kit_standard/cancard_params/conti_radar_conf.pb.txt

2020-09-04 08:54 UTC, SeasoulChris commented on modules/calibration/data/dev_kit_standard/camera_params/front_12mm_extrinsics.yaml
> +    z: -0.6547802686691284
It is better to give default external parameters according to dev_kit_standard

2020-09-04 09:00 UTC, SeasoulChris commented on modules/calibration/data/dev_kit_standard/camera_params/front_6mm_extrinsics.yaml
> +    z: -0.75
It is better to give default external parameters according to dev_kit_standard

2020-09-04 09:01 UTC, SeasoulChris commented on modules/calibration/data/dev_kit_standard/velodyne_params/velodyne16_novatel_extrinsics.yaml
> +    z: 0.8
It is better to give default external parameters according to dev_kit_standard

2020-09-07 08:47 UTC, diegohu approved these changes

2020-09-07 11:00 UTC, closed without merging