neolix canbus
ApolloAuto/apollo pull request #12431
Opened 2020-09-08 08:36 UTC by wangjia1990

2020-09-08 09:11 UTC, lx18233184051 commented
lint: modules/canbus/vehicle/neolix_edu/protocol/aeb_frontwheelspeed_353_test.cc:48:  Lines should be <= 80 characters long

2020-09-09 08:24 UTC, macDure requested changes

2020-09-09 08:24 UTC, macDure commented on modules/canbus/vehicle/neolix_edu/neolix_edu_controller.cc
> + * Copyright 2019 The Apollo Authors. All Rights Reserved.
2020，please change all files.

2020-09-09 08:24 UTC, macDure commented on modules/canbus/vehicle/neolix_edu/protocol/BUILD
> +        ["*.cc"],
please list all .cc files in srcs and hdrs

2020-09-10 05:36 UTC, macDure approved these changes

2020-09-10 06:02 UTC, merged

2020-09-10 06:04 UTC, Capri2014 commented
@wangjia1990 @macDure I am merging this one in, but please have the correct commit message format requirement for next pr, it should be: `ModuleName: Commit messages.`