D-Kit : Move and modified the D-Kit folder and its files
ApolloAuto/apollo pull request #12477
Opened 2020-09-10 15:51 UTC by lishuanghua

1、Move the D-Kit folder from apollo/docs/specs/ to apollo/docs/.
2、Rename all the md files of the D-Kit folder.
3、Modified the pictures of the D-Kit folder, including the size and the name.

2020-09-10 16:28 UTC, storypku requested changes
Please fix these broken links:

```
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Waypoint_Following/Localization_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Sensor_Integration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Virtual_Lane_Generation_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Start_Auto_Driving_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Start_Auto_Driving_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Integration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Virtual_Lane_Generation_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/apollo_installation_cn.md' contains a link to 'D-kit/Waypoint_Following/Vehicle_Integration_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/control_profiling_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/control_profiling_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/localization_configuration_cn.md' contains a link to 'D-kit/Waypoint_Following/Vehicle_Calibration_Online_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_calibration_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_calibration_online_cn.md' contains a link to 'D-kit/Waypoint_Following/Start_Waypoint_Following_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_integration_cn.md' contains a link to 'coordination_cn.md' which is not found in the documentation files. 
WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_integration_cn.md' contains a link to 'D-kit/Waypoint_Following/Localization_Configuration_cn.md' which is not found in the documentation files.
```

2020-09-11 08:41 UTC, lishuanghua commented
> Please fix these broken links:
> 
> ```
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/perception_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Waypoint_Following/Localization_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Sensor_Integration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Virtual_Lane_Generation_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/sensor_integration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Camera_Based_Auto_Driving/start_auto_driving_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/perception_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Start_Auto_Driving_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/planning_configuration_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Start_Auto_Driving_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Integration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_calibration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Virtual_Lane_Generation_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/sensor_integration_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Sensor_Calibration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/start_auto_driving_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Planning_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'D-kit/Lidar_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Lidar_Based_Auto_Driving/virtual_lane_generation_cn.md' contains a link to 'D-kit/Camera_Based_Auto_Driving/Perception_Configuration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/apollo_installation_cn.md' contains a link to 'D-kit/Waypoint_Following/Vehicle_Integration_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/control_profiling_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/control_profiling_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/localization_configuration_cn.md' contains a link to 'D-kit/Waypoint_Following/Vehicle_Calibration_Online_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_calibration_online_cn.md' contains a link to 'Apollo_Fuel/Apply_BOS_Account_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_calibration_online_cn.md' contains a link to 'D-kit/Waypoint_Following/Start_Waypoint_Following_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_integration_cn.md' contains a link to 'coordination_cn.md' which is not found in the documentation files. 
> WARNING -  Documentation file 'D-kit/Waypoint_Following/vehicle_integration_cn.md' contains a link to 'D-kit/Waypoint_Following/Localization_Configuration_cn.md' which is not found in the documentation files.
> ```

I have already fixed them, please review again.

2020-09-11 08:56 UTC, storypku approved these changes

2020-09-11 08:57 UTC, storypku commented
Good job. Wait CI to pass.

2020-09-11 13:20 UTC, merged