Doc: add e2e planning readme
ApolloAuto/apollo pull request #12470
Opened 2020-09-10 11:52 UTC by JasonZhou404

2020-09-10 12:22 UTC, storypku submitted a review, later dismissed

2020-09-10 17:46 UTC, jinghaomiao submitted a review, later dismissed

2020-09-10 17:46 UTC, jinghaomiao commented on modules/planning/README.md
> +- Model input is consisted of a birdview image centered by vehicle pose and vehicle current velocity.
consists

2020-09-11 06:18 UTC, JasonZhou404 commented on modules/planning/README.md
> +- Model input is consisted of a birdview image centered by vehicle pose and vehicle current velocity.
solved

2020-09-11 15:16 UTC, storypku requested changes

2020-09-11 15:16 UTC, storypku commented on modules/planning/README.md
> +Apollo 6.0, which focuses on intellegence and data-driven development of autonomous driving, introduced two new planning modes: E2E mode and Hybrid mode, by which we demonstrate the new capability of
`intellegent` as an adj for `development` ? 
`thier` should be `their`. `brought in` should be `bring in`.

2020-09-11 15:16 UTC, storypku commented on modules/planning/README.md
> +**Note** that the current development of E2E mode is in early stage where it is fined tuned more for the dynamic nudge scenario rather than comprehensive ones. So suboptimality is expected when runni
1) **Note**: The current development ...

2) `fine-tuned`.  
3) `is in still in progress` => `is still in progress` .
4) `with developer` should be removed.

2020-09-14 18:13 UTC, jinghaomiao approved these changes

2020-09-14 18:13 UTC, merged