Dreamview:modify alert
ApolloAuto/apollo pull request #12603
Opened 2020-09-18 14:37 UTC by lj0919

修复了四个警告 升级了四个yarn依赖  跑起来测试了一下dreamview没有问题

2020-09-18 17:19 UTC, vlin17 commented
Don't forget to commit the latest bundle files and test with localhost:8888

2020-09-18 22:08 UTC, vlin17 requested changes

2020-09-18 22:08 UTC, vlin17 commented on modules/dreamview/frontend/package.json
> +        "bl": "^4.0.3",
Don't add indirectly dependencies.

The Ideal way of upgrading packages is to find out which direct dependencies use those problematic ones and upgrade direct dependencies instead.

2020-09-21 02:27 UTC, lj0919 commented on modules/dreamview/frontend/package.json
> +        "bl": "^4.0.3",
好的收到

2020-09-21 07:23 UTC, closed without merging