Calibration: update typos and correct files in calibration
ApolloAuto/apollo pull request #12806
Opened 2020-10-19 11:43 UTC by zyc0222

2020-10-19 12:27 UTC, SeasoulChris requested changes

2020-10-19 12:27 UTC, SeasoulChris commented on modules/calibration/data/dev_kit_advanced_3lidar/planning_conf/planning_config.pb.txt
> -topic_config {
need to change planning_config.pb.txt & planning.conf in branch 5.5 ，not master ;

2020-10-20 01:15 UTC, storypku requested changes

2020-10-20 01:15 UTC, storypku commented on modules/calibration/data/dev_kit_advanced_ne-s/localization_conf/localization.conf~HEAD
> +--flagfile=/apollo/modules/common/data/global_flagfile.txt
FIle with this name should not be leaked into your PR.

2020-10-20 03:03 UTC, closed without merging