Docs: add quick_start docs for neolix_edu
ApolloAuto/apollo pull request #13078
Opened 2020-11-30 03:27 UTC by zyc0222

2020-12-01 05:46 UTC, diegohu requested changes

2020-12-01 05:46 UTC, diegohu commented on docs/D-kit/Vehicle_Guide/D-KIT_Advanced/Quick_Start_Neolix_Edu.md
> +ChannelName:/Apollo/canbus/chassis_detail
涉及到Apollo系统里的信息，建议加入小标题『从Apollo系统查看相关信息』，同时强调 请确保已经在车辆配套计算单元中正确安装了Apollo系统。

2020-12-01 06:11 UTC, diegohu requested changes

2020-12-04 03:23 UTC, macDure approved these changes

2020-12-04 04:11 UTC, merged