docs:D-kit:add the D-KIT_Standard vehicle guide
ApolloAuto/apollo pull request #13089
Opened 2020-12-01 05:37 UTC by cuishiwei

2020-12-01 10:31 UTC, storypku requested changes
Please use lower-case file/picture names. Don't use `ABC_BCD.JPG` or `ABC_1.jpg`.

Don't provide both `abc.png` and `abc.jpg`, one is enough.

2020-12-02 13:31 UTC, cuishiwei commented
> Please use lower-case file/picture names. Don't use `ABC_BCD.JPG` or `ABC_1.jpg`.
> 
> Don't provide both `abc.png` and `abc.jpg`, one is enough.

fixed

2020-12-02 13:51 UTC, macDure commented
> Please use lower-case file/picture names. Don't use `ABC_BCD.JPG` or `ABC_1.jpg`.
> 
> Don't provide both `abc.png` and `abc.jpg`, one is enough.

fix it.

2020-12-02 13:51 UTC, macDure approved these changes

2020-12-03 05:48 UTC, merged