canbus: add aeb control command in devkit
ApolloAuto/apollo pull request #13172
Opened 2020-12-11 10:30 UTC by macDure

2020-12-15 02:26 UTC, diegohu requested changes

2020-12-15 02:26 UTC, diegohu commented on modules/calibration/data/dev_kit_standard/cancard_params/canbus.conf
> +--enable_devkit_standard_aeb
change to enable_aeb

2020-12-15 02:35 UTC, macDure commented on modules/calibration/data/dev_kit_standard/cancard_params/canbus.conf
> +--enable_devkit_standard_aeb
has fixed

2020-12-16 15:42 UTC, diegohu approved these changes

2020-12-16 15:42 UTC, merged