Refactor Lidar drivers
ApolloAuto/apollo pull request #13245
Opened 2020-12-25 03:24 UTC by lx18233184051

1: keep original component to adapt dreamview.
2: modify all brand lidar(velodyne hesai robosense) driver to adbstact factory , so that developer can use LidarDriverFactory to add new lidar easily.
3: TODO: abstact parse module.

2020-12-25 03:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=13245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ApolloAuto/apollo?pullRequest=13245) before we can accept your contribution.<br/><hr/>**liuxu** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ApolloAuto/apollo?pullRequest=13245) it.</sub>

2020-12-25 05:52 UTC, changsh726 commented on modules/drivers/lidar/common/driver_factory/driver_base.h
> + * Copyright 2017 The Apollo Authors. All Rights Reserved.
2020

2020-12-25 05:59 UTC, changsh726 commented on modules/drivers/lidar/velodyne/driver/driver.h
> +  explicit Velodyne64Driver(const std::shared_ptr<cyber::Node> &node,
no need explicit here

2020-12-25 06:01 UTC, changsh726 commented on modules/drivers/lidar/velodyne/driver/driver.h
> +  void device_poll();
DevicePoll()

2020-12-25 06:10 UTC, changsh726 commented on modules/drivers/lidar/velodyne/driver/driver.h
> +  explicit VelodyneDriver(const std::shared_ptr<cyber::Node> &node,
no need explicit here

2020-12-25 06:46 UTC, storypku commented on modules/drivers/lidar/common/driver_factory/BUILD
> +        "//modules/drivers/lidar/proto:lidar_parameter",
Please run buildifer or apollo.sh format on this file.

2020-12-25 08:58 UTC, storypku commented on modules/drivers/lidar/common/driver_factory/driver_base.h
> +  explicit LidarDriver(const std::shared_ptr<::apollo::cyber::Node>& node) {}
node_ should be initialized with node.

2020-12-25 08:59 UTC, storypku requested changes

2020-12-25 08:59 UTC, storypku commented on modules/drivers/lidar/common/driver_factory/driver_base.h
> +   * @return If the initialization is successful.
Comment is misleading.

2020-12-31 02:13 UTC, lfcarol submitted a review, later dismissed

2020-12-31 05:40 UTC, lfcarol approved these changes

2020-12-31 06:00 UTC, merged