Extend release build to cover more modules and other improvements
ApolloAuto/apollo pull request #13535
Opened 2021-03-09 14:02 UTC by shr-project

2021-03-09 20:52 UTC, shr-project commented
@storypku Hi,

great work on bazel installation for release! Thanks a lot!

I've added some changes for docker for cleaner volume use and for creating standalone container (like what we're using at LGE with Apollo 5.0).

These first changes should be relatively ready for review, but I wasn't able to test them end-to-end, because the runtime image is missing some modules we're using, so now I'm adding bazel install targets to them as well and that's why I've created this PR only as a draft.

Please let me know what's your current plans for release/runtime support and how I can help with that.

Also I haven't found any information about plans for 6.1 release (other than v6.1_dev branch existence). Is there some newer roadmap than https://apollo.auto/about/development_route.html (which ends in 2019)?

2021-03-10 05:47 UTC, storypku requested changes

2021-03-10 05:49 UTC, storypku commented
> @storypku Hi,
> 
> great work on bazel installation for release! Thanks a lot!
> 
> I've added some changes for docker for cleaner volume use and for creating standalone container (like what we're using at LGE with Apollo 5.0).
> 
> These first changes should be relatively ready for review, but I wasn't able to test them end-to-end, because the runtime image is missing some modules we're using, so now I'm adding bazel install targets to them as well and that's why I've created this PR only as a draft.
> 
> Please let me know what's your current plans for release/runtime support and how I can help with that.
> 
> Also I haven't found any information about plans for 6.1 release (other than v6.1_dev branch existence). Is there some newer roadmap than https://apollo.auto/about/development_route.html (which ends in 2019)?

Hi Martin @shr-project 
As discussed earlier this morning, Please split the PRs for release build output to those for Runtime Docker.
Thank you.

2021-03-12 17:16 UTC, shr-project commented
Separate PRs (first was already merged yesterday):
https://github.com/ApolloAuto/apollo/pull/13537 Bazel: add install target to few more modules
https://github.com/ApolloAuto/apollo/pull/13538 Docker: improve docker volume handling and allow to create standalone image with all volumes included

Closing this PR (only the rejected "Docker: runtime_start.sh: use runtime-x86_64 image instead of dev-x86_64" commit was left here).

2021-03-12 17:16 UTC, closed without merging