I think here should be an add instead of minus
ApolloAuto/apollo pull request #13541
Opened 2021-03-11 07:34 UTC by lycismail

I think here should use add. Because if we suppose that the vehicle should driving in clockwise，means the ref traj like a circle，and the real point of our car is outside the circle .Then if we use cross product of the (cos_ref_theta, sin_ref_theta) and (dx, dy) , the result is a positive num. But the fuction here want it to be a negative one, because that make the one_minus_kappa_r_d = R_real / R_ref， the R_real is bigger than R_ref

2021-03-11 23:21 UTC, HongyiSun commented
It's quite hard to denote the math formula here.
Please refer to the APPENDIX I of Werling's Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame paper here[https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame]

2021-03-11 23:22 UTC, HongyiSun requested changes
It's quite hard to denote the math formula here.
Please refer to the APPENDIX I of Werling's Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame paper [here](https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame)

2021-03-12 03:30 UTC, lycismail commented
Thx a lot. But i dont know why should keep 1 - Kr*d > 0 , whitch means Rr - d > 0. Is it a stability criteria ？

2021-03-12 03:31 UTC, lycismail commented
> It's quite hard to denote the math formula here.
> Please refer to the APPENDIX I of Werling's _Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame_ paper [here](https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame)

Thx a lot. But i dont know why should keep 1 - Kr*d > 0 , whitch means Rr - d > 0. Is it a stability criteria ？

2021-03-12 03:32 UTC, closed without merging

2021-03-12 03:59 UTC, HongyiSun commented
> > It's quite hard to denote the math formula here.
> > Please refer to the APPENDIX I of Werling's _Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame_ paper [here](https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame)
> 
> Thx a lot. But i dont know why should keep 1 - Kr*d > 0 , whitch means Rr - d > 0. Is it a stability criteria ？

Yes, It's kind of a stability criteria.
As for we transform our path between Cartesian Space and Frenet Frame, there has to be a criteria that our points should stay close to the reference line, and the angle difference should remain small, or the transformation is not valid any more.

2021-03-15 03:11 UTC, lycismail commented
> > > It's quite hard to denote the math formula here.
> > > Please refer to the APPENDIX I of Werling's _Optimal Trajectory Generation for Dynamic Street Scenarios in a Frenet Frame_ paper [here](https://www.researchgate.net/publication/224156269_Optimal_Trajectory_Generation_for_Dynamic_Street_Scenarios_in_a_Frenet_Frame)
> > 
> > 
> > Thx a lot. But i dont know why should keep 1 - Kr*d > 0 , whitch means Rr - d > 0. Is it a stability criteria ？
> 
> Yes, It's kind of a stability criteria.
> As for we transform our path between Cartesian Space and Frenet Frame, there has to be a criteria that our points should stay close to the reference line, and the angle difference should remain small, or the transformation is not valid any more.

Thank u so much. I will think it carefully. Would you mind I ask another question here? I wonder why use osqp method to solve the MPC matrix without build QP problem like before which used QPOASES and made an H & f with reference to matrix A and B. Now we just use matrix Q & P to solve. I can not understand the QP progress. Could u give me a reference, like a paper or something? Very appreciate！