Docs: Introduction to Apollo Release Build added
ApolloAuto/apollo pull request #13566
Opened 2021-03-16 11:49 UTC by storypku

2021-03-20 12:46 UTC, shr-project requested changes

2021-03-20 12:46 UTC, shr-project commented on docs/technical_tutorial/intro_to_apollo_release_build.md
> +Lgsvl-Simulator find that the total size of all Docker images, volumes and Bazel
It's called "SVL Simulator" now.

2021-03-20 12:46 UTC, shr-project commented on docs/technical_tutorial/intro_to_apollo_release_build_cn.md
> +种部署上的不足，在若干情形下对用户相当不便。Lgsvl 模拟器的开发者发现，将 Apollo
"SVL Simulator" as in English version.

2021-03-22 12:37 UTC, storypku commented on docs/technical_tutorial/intro_to_apollo_release_build_cn.md
> +种部署上的不足，在若干情形下对用户相当不便。Lgsvl 模拟器的开发者发现，将 Apollo
Renamed following Martin's comments.

2021-03-22 13:43 UTC, zhoujie5517 approved these changes

2021-03-23 01:43 UTC, merged