docs: add planning_speed_bounds_decider.md
ApolloAuto/apollo pull request #13643
Opened 2021-03-31 08:38 UTC by JackFu123

2021-03-31 09:14 UTC, JasonZhou404 requested changes

2021-03-31 13:44 UTC, JasonZhou404 requested changes

2021-03-31 13:44 UTC, JasonZhou404 commented on docs/technical_documents/planning_piecewise_jerk_nonlinear_speed_optimizer.md
> +# Title(replace it)
?

2021-03-31 13:45 UTC, JasonZhou404 requested changes

2021-03-31 13:45 UTC, JasonZhou404 commented on docs/technical_documents/planning_piecewise_jerk_nonlinear_speed_optimizer.md
> +_**Tip**: to read the equations in the document, you are recommended to use Chrome with [a plugin](https://chrome.google.com/webstore/detail/tex-all-the-things/cbimabofgmfdkicghcadidpemeenbffn) or co
Delete it.

2021-04-01 02:47 UTC, JackFu123 commented on docs/technical_documents/planning_piecewise_jerk_nonlinear_speed_optimizer.md
> +_**Tip**: to read the equations in the document, you are recommended to use Chrome with [a plugin](https://chrome.google.com/webstore/detail/tex-all-the-things/cbimabofgmfdkicghcadidpemeenbffn) or co
Sure.

2021-04-01 06:22 UTC, JasonZhou404 approved these changes

2021-04-02 04:27 UTC, merged