dreamview: fix bug at sim control
ApolloAuto/apollo pull request #13727
Opened 2021-04-25 07:59 UTC by qwetqwe

InitStartPoint() can handle  using localization point and using dummy point.if localization is not empty, program will jump here.

2021-04-26 06:45 UTC, storypku commented
@lj0919 Please help review this PR. Thank you.

2021-04-27 03:12 UTC, lj0919 commented
@qwetqwe https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/dreamview/backend/sim_control/sim_control.cc#L255 when localization reader has no data, set_start_point is passed in true, we will init start point

2021-04-27 05:47 UTC, qwetqwe commented
Hi, @lj0919 
In SimControl::InitStartPoint ,the function seems that if localization not empty, sim control will use lastest localization message.
https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/dreamview/backend/sim_control/sim_control.cc#L140-L164
The function explaination :
https://github.com/ApolloAuto/apollo/blob/f02eda58ca1abf939c567fc8db3a461fcbcbc95a/modules/dreamview/backend/sim_control/sim_control.cc#L120-L121
But program can not get into this branch, and set start point  when localization not empty, and will output localization 0 0 0 as default.

2021-05-06 05:46 UTC, lj0919 commented
@qwetqwe  Hi, Sorry for the late reply, I misunderstood what you meant at first, the else branch looks really redundant.

2021-05-06 05:50 UTC, lj0919 commented on modules/dreamview/backend/sim_control/sim_control.cc
>  void SimControl::Init(bool set_start_point, double start_velocity,
The first argument set_start_point is no longer needed, remove it to make the function cleaner,  then test to make sure there is no problem with sim_control

2021-05-06 05:51 UTC, lj0919 requested changes
Remove unused argument to make the function cleaner

2021-05-18 08:02 UTC, lj0919 approved these changes

2021-05-18 08:03 UTC, merged