perception: correct camera perception tf to adjust soft trigger
ApolloAuto/apollo pull request #13854
Opened 2021-06-15 11:20 UTC by SeasoulChris

make camera perception tf adjust soft trigger

2021-06-16 02:39 UTC, chenxiaoying21 commented on modules/perception/onboard/transform_wrapper/transform_wrapper.cc
> +    if((query_time.ToSecond() - latest_buffer_time < 0.015) && (query_time.ToSecond() - latest_buffer_time > 0))
query_time.ToSecond()可以用一个临时变量赋值，避免二次调用

2021-06-16 02:45 UTC, chenxiaoying21 requested changes

2021-06-16 02:45 UTC, chenxiaoying21 commented on modules/perception/onboard/transform_wrapper/transform_wrapper.cc
> +      query_time = apollo::cyber::Time(0);
这种情况下，不需要再次调用lookupTransform了吧，直接计算trans->translation和trans->rotation，然后返回true就可以了吧？

2021-06-16 05:16 UTC, changsh726 commented on modules/perception/onboard/transform_wrapper/transform_wrapper.cc
> +    else
} else {

2021-06-22 03:36 UTC, chenxiaoying21 approved these changes

2021-06-22 03:37 UTC, merged